name: Build and Deploy

on:
  push:
    branches:
      - master
  workflow_dispatch: {}

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    name: Build and deploy RcTracking.UI to Azure Static Web Apps

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '10.0.x'
          
      - name: Check folder path
        run: ls ${github_workspace}src/RcTracking.UI/wwwroot/
        
      - name: Update appsettings
        uses: restackio/update-json-file-action@2.1
        with:
           file: ${github_workspace}src/RcTracking.UI/wwwroot/appsettings.json
           fields: "{\"AzureAd.Authority\": \"${{ secrets.AZURE_AD_AUTHORITY }}\", \"AzureAd.ClientId\": \"${{ secrets.AZURE_AD_CLIENT_ID }}\"}"
      
      - name: Restore dependencies
        run: dotnet restore src/RcTracking.UI/RcTracking.UI.csproj

      - name: Publish Blazor WebAssembly (Release)
        run: dotnet publish src/RcTracking.UI/RcTracking.UI.csproj -c Release -o src/RcTracking.UI/publish

      - name: Deploy to Azure Static Web Apps
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN_LIVELY_GLACIER_04001E210 }} # set this secret in your repo settings
          repo_token: ${{ secrets.GITHUB_TOKEN }} # Used for GitHub integrations (required)
          action: "upload"
          skip_app_build: true
          skip_api_build: true
          app_location: "src/RcTracking.UI/publish/wwwroot" # App source location
          output_location: ""
          api_location: "" # No Functions API in this workflow (set if you have one)
